---
- name: check if a file exist
  hosts: win
  vars:
          myfile: 'C:\Users\Administrator\Desktop\anket.txt'
  tasks: 
    - name: check if file exist
      win_stat:
              path: "{{myfile}}"
      register: file_data
    - name: report file exist
      debug:
              msg: " the file {{myfile}} exist "
      when: file_data.stat.exists
    - name: report file not exists
      debug:
              msg: "The file {{myfile}} doesn't exist" 
      when: not file_data.stat.exists              
