---
- name: win_copy module demo
  hosts: win
  become: false
  vars:
     source: "report.txt"
     destination: "C:/Users/Administrator/Desktop/report.txt"
  tasks: 
   - name: copy the report.txt
     win_copy:
        src: "{{source}}"
        dest: "{{destination}}"
